create table if not exists public.units (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.presentations (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.product_types (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.locations (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

create sequence if not exists public.product_code_seq start 1;
create sequence if not exists public.sale_code_seq start 1;
create sequence if not exists public.movement_code_seq start 1;

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  sku text unique,
  barcode text,
  price numeric(12, 2) not null check (price >= 0),
  cost numeric(12, 2) check (cost is null or cost >= 0),
  type text not null,
  unit_id bigint references public.units(id) on delete set null,
  presentation_id bigint references public.presentations(id) on delete set null,
  location text not null,
  description text not null,
  dose text,
  stock_quantity integer not null default 0 check (stock_quantity >= 0),
  min_stock integer not null default 10 check (min_stock >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.sales (
  id bigint generated by default as identity primary key,
  sale_code text unique,
  customer_name text,
  payment_method text not null default 'efectivo',
  total numeric(12, 2) not null check (total >= 0),
  user_id uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create table if not exists public.sale_items (
  id bigint generated by default as identity primary key,
  sale_id bigint not null references public.sales(id) on delete cascade,
  product_id bigint not null references public.products(id),
  quantity integer not null check (quantity > 0),
  unit_price numeric(12, 2) not null check (unit_price >= 0),
  subtotal numeric(12, 2) generated always as (quantity * unit_price) stored
);

create table if not exists public.inventory_movements (
  id bigint generated by default as identity primary key,
  movement_code text unique,
  product_id bigint not null references public.products(id),
  movement_type text not null check (movement_type in ('entry', 'exit', 'adjustment')),
  quantity integer not null check (quantity > 0),
  reason text,
  sale_id bigint references public.sales(id) on delete set null,
  user_id uuid references auth.users(id),
  created_at timestamptz not null default now()
);

alter table public.products add column if not exists sku text;
alter table public.products add column if not exists barcode text;
alter table public.products add column if not exists cost numeric(12, 2);
alter table public.products add column if not exists type text;
alter table public.products add column if not exists unit_id bigint references public.units(id) on delete set null;
alter table public.products add column if not exists presentation_id bigint references public.presentations(id) on delete set null;
alter table public.products add column if not exists presentation text;
alter table public.products add column if not exists location text;
alter table public.products add column if not exists description text;
alter table public.products add column if not exists dose text;
alter table public.products add column if not exists stock_quantity integer not null default 0;
alter table public.products add column if not exists min_stock integer not null default 10;
alter table public.products add column if not exists updated_at timestamptz not null default now();
alter table public.sales add column if not exists sale_code text;
alter table public.sales add column if not exists customer_name text;
alter table public.sales add column if not exists payment_method text not null default 'efectivo';
alter table public.sales add column if not exists total numeric(12, 2) not null default 0;
alter table public.sales add column if not exists user_id uuid references auth.users(id);
alter table public.sales add column if not exists created_at timestamptz not null default now();
alter table public.sale_items add column if not exists sale_id bigint references public.sales(id) on delete cascade;
alter table public.sale_items add column if not exists product_id bigint references public.products(id);
alter table public.sale_items add column if not exists quantity integer not null default 1;
alter table public.sale_items add column if not exists price numeric(12, 2) not null default 0;
alter table public.sale_items add column if not exists unit_price numeric(12, 2) not null default 0;
alter table public.inventory_movements add column if not exists movement_code text;
alter table public.inventory_movements add column if not exists product_id bigint references public.products(id);
alter table public.inventory_movements add column if not exists movement_type text;
alter table public.inventory_movements add column if not exists quantity integer not null default 1;
alter table public.inventory_movements add column if not exists reason text;
alter table public.inventory_movements add column if not exists sale_id bigint references public.sales(id) on delete set null;
alter table public.inventory_movements add column if not exists user_id uuid references auth.users(id);
alter table public.inventory_movements add column if not exists created_at timestamptz not null default now();

alter table public.products alter column presentation drop not null;
alter table public.products alter column barcode drop not null;
alter table public.products alter column cost drop not null;
alter table public.products alter column dose drop not null;
alter table public.sales alter column customer_name drop not null;
alter table public.sales alter column payment_method set default 'efectivo';
alter table public.sales alter column total set default 0;
alter table public.sale_items alter column quantity set default 1;
alter table public.sale_items alter column price set default 0;
alter table public.sale_items alter column unit_price set default 0;
alter table public.inventory_movements alter column quantity set default 1;

update public.products
set presentation = public.presentations.name
from public.presentations
where public.products.presentation_id = public.presentations.id
  and (public.products.presentation is null or trim(public.products.presentation) = '');

create unique index if not exists products_sku_key on public.products(sku);
create unique index if not exists sales_sale_code_key on public.sales(sale_code);
create unique index if not exists inventory_movements_movement_code_key on public.inventory_movements(movement_code);

create or replace function public.next_product_code()
returns text
language plpgsql
as $$
begin
  return 'FO-MED-' || lpad(nextval('public.product_code_seq')::text, 6, '0');
end;
$$;

create or replace function public.next_sale_code()
returns text
language plpgsql
as $$
begin
  return 'FO-VTA-' || to_char(now(), 'YYYY') || '-' || lpad(nextval('public.sale_code_seq')::text, 6, '0');
end;
$$;

create or replace function public.next_movement_code()
returns text
language plpgsql
as $$
begin
  return 'FO-MOV-' || to_char(now(), 'YYYY') || '-' || lpad(nextval('public.movement_code_seq')::text, 6, '0');
end;
$$;

create or replace function public.assign_product_code()
returns trigger
language plpgsql
as $$
begin
  if new.sku is null or trim(new.sku) = '' then
    new.sku := public.next_product_code();
  end if;
  return new;
end;
$$;

create or replace function public.assign_sale_code()
returns trigger
language plpgsql
as $$
begin
  if new.sale_code is null or trim(new.sale_code) = '' then
    new.sale_code := public.next_sale_code();
  end if;
  return new;
end;
$$;

create or replace function public.assign_movement_code()
returns trigger
language plpgsql
as $$
begin
  if new.movement_code is null or trim(new.movement_code) = '' then
    new.movement_code := public.next_movement_code();
  end if;
  return new;
end;
$$;

drop trigger if exists products_assign_code on public.products;
create trigger products_assign_code
before insert on public.products
for each row execute function public.assign_product_code();

drop trigger if exists sales_assign_code on public.sales;
create trigger sales_assign_code
before insert on public.sales
for each row execute function public.assign_sale_code();

drop trigger if exists inventory_movements_assign_code on public.inventory_movements;
create trigger inventory_movements_assign_code
before insert on public.inventory_movements
for each row execute function public.assign_movement_code();

do $$
declare
  row_record record;
begin
  for row_record in select id from public.products where sku is null or trim(sku) = '' order by id
  loop
    update public.products set sku = public.next_product_code() where id = row_record.id;
  end loop;

  for row_record in select id from public.sales where sale_code is null or trim(sale_code) = '' order by id
  loop
    update public.sales set sale_code = public.next_sale_code() where id = row_record.id;
  end loop;

  for row_record in select id from public.inventory_movements where movement_code is null or trim(movement_code) = '' order by id
  loop
    update public.inventory_movements set movement_code = public.next_movement_code() where id = row_record.id;
  end loop;
end;
$$;

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists products_touch_updated_at on public.products;
create trigger products_touch_updated_at
before update on public.products
for each row execute function public.touch_updated_at();

create or replace function public.register_inventory_movement(
  p_product_id bigint,
  p_movement_type text,
  p_quantity integer,
  p_reason text,
  p_user_id uuid
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  current_stock integer;
  next_stock integer;
begin
  if p_quantity <= 0 then
    raise exception 'La cantidad debe ser mayor que cero';
  end if;

  select stock_quantity into current_stock
  from public.products
  where id = p_product_id
  for update;

  if current_stock is null then
    raise exception 'Producto no encontrado';
  end if;

  if p_movement_type = 'entry' then
    next_stock := current_stock + p_quantity;
  elsif p_movement_type in ('exit', 'adjustment') then
    next_stock := current_stock - p_quantity;
  else
    raise exception 'Tipo de movimiento invalido';
  end if;

  if next_stock < 0 then
    raise exception 'Stock insuficiente. Disponible: %', current_stock;
  end if;

  update public.products set stock_quantity = next_stock where id = p_product_id;

  insert into public.inventory_movements(product_id, movement_type, quantity, reason, user_id)
  values (p_product_id, p_movement_type, p_quantity, p_reason, p_user_id);
end;
$$;

create or replace function public.register_sale(
  p_customer_name text,
  p_payment_method text,
  p_user_id uuid,
  p_items jsonb
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  new_sale_id bigint;
  item jsonb;
  product_stock integer;
  item_product_id bigint;
  item_quantity integer;
  item_price numeric(12, 2);
  sale_total numeric(12, 2) := 0;
begin
  if jsonb_array_length(p_items) = 0 then
    raise exception 'La venta no tiene productos';
  end if;

  insert into public.sales(customer_name, payment_method, total, user_id)
  values (p_customer_name, p_payment_method, 0, p_user_id)
  returning id into new_sale_id;

  for item in select * from jsonb_array_elements(p_items)
  loop
    item_product_id := (item->>'product_id')::bigint;
    item_quantity := (item->>'quantity')::integer;
    item_price := (item->>'unit_price')::numeric(12, 2);

    if item_quantity <= 0 then
      raise exception 'La cantidad debe ser mayor que cero';
    end if;

    select stock_quantity into product_stock
    from public.products
    where id = item_product_id
    for update;

    if product_stock is null then
      raise exception 'Producto no encontrado';
    end if;

    if product_stock < item_quantity then
      raise exception 'Stock insuficiente para el producto %. Disponible: %', item_product_id, product_stock;
    end if;

    update public.products
    set stock_quantity = stock_quantity - item_quantity
    where id = item_product_id;

    insert into public.sale_items(sale_id, product_id, quantity, price, unit_price)
    values (new_sale_id, item_product_id, item_quantity, item_price, item_price);

    insert into public.inventory_movements(product_id, movement_type, quantity, reason, sale_id, user_id)
    values (item_product_id, 'exit', item_quantity, 'Venta', new_sale_id, p_user_id);

    sale_total := sale_total + (item_quantity * item_price);
  end loop;

  update public.sales set total = sale_total where id = new_sale_id;

  return new_sale_id;
end;
$$;

alter table public.units enable row level security;
alter table public.presentations enable row level security;
alter table public.product_types enable row level security;
alter table public.locations enable row level security;
alter table public.products enable row level security;
alter table public.sales enable row level security;
alter table public.sale_items enable row level security;
alter table public.inventory_movements enable row level security;

drop policy if exists "authenticated can manage units" on public.units;
drop policy if exists "authenticated can manage presentations" on public.presentations;
drop policy if exists "authenticated can manage product types" on public.product_types;
drop policy if exists "authenticated can manage locations" on public.locations;
drop policy if exists "authenticated can manage products" on public.products;
drop policy if exists "authenticated can manage sales" on public.sales;
drop policy if exists "authenticated can manage sale items" on public.sale_items;
drop policy if exists "authenticated can manage inventory movements" on public.inventory_movements;

create policy "authenticated can manage units" on public.units for all to authenticated using (true) with check (true);
create policy "authenticated can manage presentations" on public.presentations for all to authenticated using (true) with check (true);
create policy "authenticated can manage product types" on public.product_types for all to authenticated using (true) with check (true);
create policy "authenticated can manage locations" on public.locations for all to authenticated using (true) with check (true);
create policy "authenticated can manage products" on public.products for all to authenticated using (true) with check (true);
create policy "authenticated can manage sales" on public.sales for all to authenticated using (true) with check (true);
create policy "authenticated can manage sale items" on public.sale_items for all to authenticated using (true) with check (true);
create policy "authenticated can manage inventory movements" on public.inventory_movements for all to authenticated using (true) with check (true);

insert into public.units(name) values ('Unidad'), ('Tableta'), ('Capsula'), ('ml'), ('mg'), ('Frasco') on conflict do nothing;
insert into public.presentations(name) values ('Caja'), ('Blister'), ('Frasco'), ('Ampolla'), ('Sobre'), ('Tubo') on conflict do nothing;
insert into public.locations(name) values
  ('Estante 1'),
  ('Estante 2'),
  ('Estante 3'),
  ('Vitrina mostrador'),
  ('Vitrina trasera'),
  ('Refrigerador'),
  ('Bodega')
on conflict do nothing;
insert into public.product_types(name) values
  ('Analgesico'),
  ('Antibiotico'),
  ('Anticonceptivo'),
  ('Antidiarreico'),
  ('Antigripal'),
  ('Antihistaminico'),
  ('Antiinflamatorio'),
  ('Antimicotico'),
  ('Antiparasitario'),
  ('Antiseptico'),
  ('Broncodilatador'),
  ('Dermatologico'),
  ('Expectorante'),
  ('Gastrointestinal'),
  ('Hipertension'),
  ('Oftalmico'),
  ('Otico'),
  ('Pediatrico'),
  ('Suero oral'),
  ('Vitaminas')
on conflict do nothing;

notify pgrst, 'reload schema';
